Add CI build gradle caching

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,30 +21,38 @@ jobs:
         ]
     runs-on: ${{ matrix.os }}
     steps:
-      - name: checkout repository
+      - name: Checkout Repository
         uses: actions/checkout@v2
-      - name: validate gradle wrapper
+      - name: Gradle Cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
+          restore-keys: ${{ runner.os }}-gradle-
+      - name: Validate Gradle Wrapper
         uses: gradle/wrapper-validation-action@v1
-      - name: setup jdk ${{ matrix.java }}
+      - name: Setup JDK ${{ matrix.java }}
         uses: actions/setup-java@v1
         with:
           java-version: ${{ matrix.java }}
-      - name: make gradle wrapper executable
+      - name: Make Gradle Wrapper Executable
         if: ${{ runner.os != 'Windows' }}
         run: chmod +x ./gradlew
-      - name: build
+      - name: Build
         run: ./gradlew build
-      - name: capture build artifacts
-        if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from officially supported java on one OS
+      - name: Capture Build Artifacts
+        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from officially supported java on one OS
         uses: actions/upload-artifact@v2
         with:
           name: Artifacts
           path: build/libs/
 #      - name: generate allure report
-#        if: ${{ (failure() && !cancelled()) || (runner.os == 'Linux' && matrix.java == '16') }}
+#        if: ${{ (failure() && !cancelled()) || (runner.os == 'Linux' && matrix.java == '17') }}
 #        run: ./gradlew allureReport
-      - name: capture test reports
-        if: ${{ (failure() && !cancelled()) || (runner.os == 'Linux' && matrix.java == '16') }}
+      - name: Capture Test Reports
+        if: ${{ (failure() && !cancelled()) || (runner.os == 'Linux' && matrix.java == '17') }}
         uses: actions/upload-artifact@v2
         with:
           name: Test-Reports-${{ matrix.os }}-${{ matrix.java }}
